# Generated by Django 4.0 on 2022-01-07 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingAndComments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('HLP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_to', to='accounts.customuser')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='front.ratingandcomments')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_from', to='accounts.customuser')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
