# Generated by Django 4.0.1 on 2022-01-25 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='apply_to',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='target_order',
        ),
    ]
