# Generated by Django 4.0.1 on 2022-01-25 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_hospitals_specialist'),
        ('discount', '0002_remove_campaign_apply_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='target_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dicount_hospital', to='accounts.hospitals'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='target_hospitaldoctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dicount_hospitaldoctor', to='accounts.hospitaldoctors'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='target_lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dicount_lab', to='accounts.labs'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='target_pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dicount_pharmacy', to='accounts.pharmacy'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='target_specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dicount_specialist', to='accounts.specailist'),
        ),
    ]
