# Generated by Django 3.2.5 on 2021-12-01 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_auto_20211201_2209'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospitalbooking', to='patient.orderbooking'),
        ),
    ]
