# Generated by Django 3.2.5 on 2021-11-26 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='specailist',
            name='category',
            field=models.CharField(blank=True, default='Health Tips', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='specialist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.specailist'),
        ),
    ]
