# Generated by Django 4.0.1 on 2022-01-18 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_share_alter_customuser_counter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='ID_number',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='ID_proof',
            field=models.FileField(blank=True, default='', null=True, upload_to='patients/profile/images'),
        ),
        migrations.AddField(
            model_name='patients',
            name='added_by_hospital',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='hospital',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.hospitals'),
        ),
        migrations.AddField(
            model_name='patients',
            name='status',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
