# Generated by Django 3.2.5 on 2021-12-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211126_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitals',
            name='profile_pic',
            field=models.FileField(default='', max_length=500, null=True, upload_to='Hospital/profile/images'),
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='registration_proof',
            field=models.FileField(blank=True, default='', max_length=500, null=True, upload_to='hospital/documents/images'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='profile_pic',
            field=models.FileField(blank=True, default='', null=True, upload_to='patients/profile/images'),
        ),
        migrations.AlterField(
            model_name='specailist',
            name='hover_icon',
            field=models.FileField(default='', max_length=500, null=True, upload_to='Hospital/specialist/images/hover'),
        ),
        migrations.AlterField(
            model_name='specailist',
            name='specialist_icon',
            field=models.FileField(default='', max_length=500, null=True, upload_to='Hospital/specialist/images'),
        ),
    ]
