# Generated by Django 4.0 on 2022-01-07 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_hospitaldoctors_specialist'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaldoctors',
            name='specialist',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.specailist'),
        ),
    ]
