# Generated by Django 4.0.1 on 2022-01-25 18:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_hospitals_specialist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitaldoctors',
            name='admin',
        ),
        migrations.AddField(
            model_name='hospitaldoctors',
            name='admin',
            field=models.ManyToManyField(blank=True, default='', null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='hospitals',
            name='admin',
        ),
        migrations.AddField(
            model_name='hospitals',
            name='admin',
            field=models.ManyToManyField(blank=True, default='', null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='labs',
            name='admin',
        ),
        migrations.AddField(
            model_name='labs',
            name='admin',
            field=models.ManyToManyField(blank=True, default='', null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='patients',
            name='admin',
        ),
        migrations.AddField(
            model_name='patients',
            name='admin',
            field=models.ManyToManyField(blank=True, default='', null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='admin',
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='admin',
            field=models.ManyToManyField(blank=True, default='', null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
