# Generated by Django 4.0.1 on 2022-01-25 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_hospitaldoctors_admin_hospitaldoctors_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitaldoctors',
            name='admin',
        ),
        migrations.AddField(
            model_name='hospitaldoctors',
            name='admin',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='hospitals',
            name='admin',
        ),
        migrations.AddField(
            model_name='hospitals',
            name='admin',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='labs',
            name='admin',
        ),
        migrations.AddField(
            model_name='labs',
            name='admin',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='patients',
            name='admin',
        ),
        migrations.AddField(
            model_name='patients',
            name='admin',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='admin',
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='admin',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
