# Generated by Django 3.2.5 on 2021-12-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211203_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitaldoctors',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='Doctor/profile/images'),
        ),
        migrations.AlterField(
            model_name='labs',
            name='profile_pic',
            field=models.FileField(default='', max_length=500, null=True, upload_to='hospital/profile/images'),
        ),
        migrations.AlterField(
            model_name='labs',
            name='registration_proof',
            field=models.FileField(blank=True, default='', max_length=500, null=True, upload_to='hospital/documents/images'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='profile_pic',
            field=models.FileField(default='', max_length=500, null=True, upload_to='Pharmacist/profile/images'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='registration_proof',
            field=models.FileField(blank=True, default='', max_length=500, null=True, upload_to='Pharmacist/documents/images'),
        ),
    ]
