# Generated by Django 4.0.1 on 2022-01-18 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_patients_id_number_patients_id_proof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='added_by_doctor',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='doctor',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.hospitaldoctors'),
        ),
    ]
