# Generated by Django 4.0.1 on 2022-01-20 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_zip_code_hospitaldoctors_pin_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='zip_Code',
            new_name='pin_code',
        ),
    ]
