# Generated by Django 4.0 on 2022-01-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_hospitaldoctors_specialist'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaldoctors',
            name='is_hospital_added',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
