# Generated by Django 4.0.1 on 2022-01-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_zip_code_patients_pin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specailist',
            name='hover_icon',
            field=models.FileField(default='', max_length=500, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='specailist',
            name='specialist_icon',
            field=models.FileField(default='', max_length=500, null=True, upload_to=''),
        ),
    ]
