# Generated by Django 3.2.5 on 2021-12-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211203_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='blood_docation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='blood_donation',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='is_donated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
