# Generated by Django 4.0 on 2022-01-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_hospitaldoctors_is_hospital_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='force_to_psswd_chngd',
            field=models.BooleanField(default=True),
        ),
    ]
