# Generated by Django 4.0.1 on 2022-01-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_specailist_hover_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specailist',
            name='hover_icon',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='specailist',
            name='specialist_icon',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
    ]
