# Generated by Django 4.0.1 on 2022-01-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_specailist_hover_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='', max_length=500, null=True, upload_to='user/profile_pic'),
        ),
        migrations.AlterField(
            model_name='hospitaldoctors',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='profile_pic',
            field=models.ImageField(default='', max_length=500, null=True, upload_to='Hospital/profile/images'),
        ),
        migrations.AlterField(
            model_name='hospitals',
            name='registration_proof',
            field=models.ImageField(blank=True, default='', max_length=500, null=True, upload_to='hospital/documents/images'),
        ),
        migrations.AlterField(
            model_name='labs',
            name='profile_pic',
            field=models.ImageField(default='', max_length=500, null=True, upload_to='hospital/profile/images'),
        ),
        migrations.AlterField(
            model_name='labs',
            name='registration_proof',
            field=models.ImageField(blank=True, default='', max_length=500, null=True, upload_to='hospital/documents/images'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='ID_proof',
            field=models.ImageField(blank=True, default='', null=True, upload_to='patients/profile/images'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='profile_pic',
            field=models.ImageField(blank=True, default='', null=True, upload_to='patients/profile/images'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='profile_pic',
            field=models.ImageField(default='', max_length=500, null=True, upload_to='Pharmacist/profile/images'),
        ),
        migrations.AlterField(
            model_name='pharmacy',
            name='registration_proof',
            field=models.ImageField(blank=True, default='', max_length=500, null=True, upload_to='Pharmacist/documents/images'),
        ),
    ]
