# Generated by Django 3.2.5 on 2021-11-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20211122_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specailist',
            name='hover_icon',
            field=models.FileField(default='', max_length=500, null=True, upload_to='Hospital/specialist/images/hover/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='specailist',
            name='specialist_icon',
            field=models.FileField(default='', max_length=500, null=True, upload_to='Hospital/specialist/images/'),
        ),
    ]
