# Generated by Django 3.2.5 on 2021-11-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20211123_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaldoctors',
            name='about',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
