# Generated by Django 4.0.1 on 2022-01-20 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_hospitals_specialist'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbooking',
            name='hospitalstaffdoctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctorbooking', to='accounts.hospitaldoctors'),
        ),
    ]
