# Generated by Django 4.0.1 on 2022-01-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderbooking',
            options={'ordering': ['-applied_date']},
        ),
        migrations.AddField(
            model_name='orderbooking',
            name='is_refund_now',
            field=models.BooleanField(default=False),
        ),
    ]
