# Generated by Django 3.2.5 on 2021-11-27 15:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211126_0707'),
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediacalRecords',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prescription', models.FileField(blank=True, default='', max_length=256, null=True, upload_to=None)),
                ('symptoms', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('AppoinmentDate', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('for_whom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.forsome')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.hospitals')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patients')),
            ],
        ),
    ]
