# Generated by Django 3.2.5 on 2021-12-01 12:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_auto_20211201_1101'),
        ('accounts', '0002_auto_20211126_0707'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0002_mediacalrecords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.serviceandcharges'),
        ),
        migrations.CreateModel(
            name='OrderBooking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('booking_type', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('booking_for', models.CharField(blank=True, choices=[(1, 'Hospital'), (2, 'Laboratory'), (3, 'Pharmacy')], default='', max_length=256, null=True)),
                ('applied_time', models.TimeField(blank=True, null=True)),
                ('applied_date', models.DateField(blank=True, null=True)),
                ('accepted_date', models.DateTimeField(blank=True, null=True)),
                ('otp_verified_datetime', models.DateTimeField(blank=True, null=True)),
                ('taken_date', models.DateTimeField(blank=True, null=True)),
                ('rejected_date', models.DateTimeField(blank=True, null=True)),
                ('is_applied', models.BooleanField(blank=True, default=True, null=True)),
                ('is_otp_verified', models.BooleanField(blank=True, default=True, null=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('reject_within_5', models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0))),
                ('status', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('add_note', models.CharField(blank=True, default='', max_length=5000, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('modified_time', models.TimeField(blank=True, null=True)),
                ('modified_date', models.DateField(blank=True, null=True)),
                ('report', models.FileField(blank=True, default='', null=True, upload_to='')),
                ('prescription', models.FileField(blank=True, default='', max_length=256, null=True, upload_to=None)),
                ('store_invoice', models.FileField(blank=True, default='', max_length=256, null=True, upload_to=None)),
                ('amount', models.FloatField(blank=True, default=0, null=True)),
                ('payment_status', models.CharField(blank=True, choices=[('Processed', 'Processed'), ('Successed', 'Successed'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded')], default='', max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('for_whom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.forsome')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.hospitals')),
                ('hospitalstaffdoctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospitalstaffdoctors')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.orderbooking')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewLabTest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.orderbooking')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.serviceandcharges')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='phoneoptforoders',
            name='order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.orderbooking'),
        ),
    ]
