# Generated by Django 4.0.1 on 2022-01-20 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_orderbooking_hospitalstaffdoctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forsome',
            old_name='zip_Code',
            new_name='pin_code',
        ),
    ]
