# Generated by Django 3.2.5 on 2021-12-01 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0003_auto_20211201_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderbooking',
            name='hospital',
        ),
        migrations.AddField(
            model_name='orderbooking',
            name='HLP',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderbooking',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL),
        ),
    ]
