# Generated by Django 4.0.1 on 2022-01-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_orderbooking_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forsome',
            name='ID_proof',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='forsome',
            name='profile_pic',
            field=models.ImageField(default='', max_length=500, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mediacalrecords',
            name='prescription',
            field=models.ImageField(blank=True, default='', max_length=256, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='orderbooking',
            name='invoice',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='orderbooking',
            name='prescription',
            field=models.ImageField(blank=True, default='', max_length=256, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='orderbooking',
            name='store_invoice',
            field=models.ImageField(blank=True, default='', max_length=256, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='patientfile',
            name='file',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='picturesformedicine',
            name='prescription',
            field=models.ImageField(blank=True, default='', max_length=256, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='picturesformedicine',
            name='store_invoice',
            field=models.ImageField(blank=True, default='', max_length=256, null=True, upload_to=''),
        ),
    ]
