# Generated by Django 4.0.1 on 2022-01-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_rename_zip_code_forsome_pin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forsome',
            name='ID_proof',
            field=models.ImageField(blank=True, default='', null=True, upload_to='someone/ID/images'),
        ),
        migrations.AlterField(
            model_name='forsome',
            name='profile_pic',
            field=models.ImageField(default='', max_length=500, null=True, upload_to='user/profile_pic'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoicepdf',
            field=models.ImageField(blank=True, default='', max_length=164, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mediacalrecords',
            name='prescription',
            field=models.ImageField(blank=True, default='', max_length=256, null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='orderbooking',
            name='invoice',
            field=models.ImageField(blank=True, default='', null=True, upload_to='booking/invoices'),
        ),
        migrations.AlterField(
            model_name='orderbooking',
            name='prescription',
            field=models.ImageField(blank=True, default='', max_length=256, null=True, upload_to='booking/prescription'),
        ),
        migrations.AlterField(
            model_name='orderbooking',
            name='report',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='orderbooking',
            name='store_invoice',
            field=models.ImageField(blank=True, default='', max_length=256, null=True, upload_to='booking/store_invoice'),
        ),
        migrations.AlterField(
            model_name='patientbottelandinjections',
            name='BI_content',
            field=models.ImageField(blank=True, choices=[(1, 'bottle'), (2, 'Injection')], default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='patientfile',
            name='file',
            field=models.ImageField(blank=True, default='', null=True, upload_to='patients/documents/file'),
        ),
        migrations.AlterField(
            model_name='picturesformedicine',
            name='prescription',
            field=models.ImageField(blank=True, default='', max_length=256, null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='picturesformedicine',
            name='store_invoice',
            field=models.ImageField(blank=True, default='', max_length=256, null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='slot',
            name='report',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
