# Generated by Django 3.2.5 on 2021-12-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20211201_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbooking',
            name='booking_for',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='orderbooking',
            name='payment_status',
            field=models.CharField(blank=True, default='', max_length=64, null=True),
        ),
    ]
