# Generated by Django 3.2.5 on 2021-12-01 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_auto_20211201_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderbooking',
            name='order_id',
        ),
    ]
