# Generated by Django 3.2.5 on 2021-12-01 16:36

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_remove_orderbooking_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbooking',
            name='order_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='orderbooking',
            name='applied_time',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderbooking',
            name='reject_within_5',
            field=models.DateTimeField(blank=True, default=datetime.datetime(1970, 1, 1, 0, 0), null=True),
        ),
    ]
