# Generated by Django 3.2.5 on 2021-12-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_auto_20211201_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbooking',
            name='is_applied',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='orderbooking',
            name='is_otp_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
