# Generated by Django 3.2.5 on 2021-12-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_auto_20211201_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbooking',
            name='applied_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
