# Generated by Django 3.2.5 on 2021-12-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_orderbooking_is_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbooking',
            name='is_accepted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
