# Generated by Django 3.2.5 on 2021-12-02 07:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211126_0707'),
        ('patient', '0011_orderbooking_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentreliefpetient',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.orderbooking'),
        ),
        migrations.AlterField(
            model_name='treatmentreliefpetient',
            name='next_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(1970, 1, 1, 0, 0), null=True),
        ),
        migrations.AlterField(
            model_name='treatmentreliefpetient',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.patients'),
        ),
    ]
