# Generated by Django 3.2.5 on 2021-12-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_auto_20211202_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderbooking',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='orderbooking',
            name='is_rejected',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
