# Generated by Django 3.2.5 on 2021-12-02 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0013_auto_20211202_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientfile',
            name='amount_paid',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='patientfile',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.orderbooking'),
        ),
    ]
