# Generated by Django 3.2.5 on 2021-12-06 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_alter_hospitalrooms_department'),
        ('patient', '0016_alter_orderbooking_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbooking',
            name='services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.serviceandcharges'),
        ),
    ]
