# Generated by Django 3.2.5 on 2021-12-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0019_newlabtest_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp',
            name='order_id',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
