# Generated by Django 3.2.5 on 2021-12-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0020_alter_temp_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbooking',
            name='is_amount_paid',
            field=models.BooleanField(default=False),
        ),
    ]
