# Generated by Django 3.2.5 on 2021-12-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0021_orderbooking_is_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbooking',
            name='is_invoice_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
