# Generated by Django 3.2.5 on 2021-12-08 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0022_orderbooking_is_invoice_uploaded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderbooking',
            old_name='is_invoice_uploaded',
            new_name='store_invoice_uploaded',
        ),
    ]
