# Generated by Django 3.2.5 on 2021-12-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0024_orderbooking_store_invoice_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbooking',
            name='homevisitcharges',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
