# Generated by Django 3.2.5 on 2021-12-08 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0025_orderbooking_homevisitcharges'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmountCalculation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_value', models.FloatField(blank=True, default=0, null=True)),
                ('tax_percentage', models.FloatField(blank=True, default=0, null=True)),
                ('tax_value', models.FloatField(blank=True, default=0, null=True)),
                ('commission_percentage', models.FloatField(blank=True, default=0, null=True)),
                ('commission_value', models.FloatField(blank=True, default=0, null=True)),
                ('discount_percentage', models.FloatField(blank=True, default=0, null=True)),
                ('discount_value', models.FloatField(blank=True, default=0, null=True)),
                ('homevisit_value', models.FloatField(blank=True, default=0, null=True)),
                ('extra_charges', models.FloatField(blank=True, default=0, null=True)),
                ('merchant_share', models.FloatField(blank=True, default=0, null=True)),
                ('admin_share', models.FloatField(blank=True, default=0, null=True)),
                ('payable_value', models.FloatField(blank=True, default=0, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
