# Generated by Django 3.2.5 on 2021-11-22 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0025_booking_reject_within_5'),
    ]

    operations = [
        migrations.AddField(
            model_name='forsome',
            name='relationship',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
