# Generated by Django 3.2.5 on 2021-12-12 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patient', '0026_amountcalculation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingAmount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tax_value', models.FloatField(blank=True, default=0, null=True)),
                ('amountpaid', models.FloatField(blank=True, default=0, null=True)),
                ('homevisit_value', models.FloatField(blank=True, default=0, null=True)),
                ('extra_charges', models.FloatField(blank=True, default=0, null=True)),
                ('amountdicounted', models.FloatField(blank=True, default=0, null=True)),
                ('usercommission', models.FloatField(blank=True, default=0, null=True)),
                ('reliefcommission', models.FloatField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.orderbooking')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invoicepdf', models.FileField(blank=True, default='', max_length=164, null=True, upload_to='')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.bookingamount')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantAccounts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('commissionpercentage', models.FloatField(blank=True, default=0, null=True)),
                ('totalcollection', models.FloatField(blank=True, default=0, null=True)),
                ('totalpaid', models.FloatField(blank=True, default=0, null=True)),
                ('totalremaining', models.FloatField(blank=True, default=0, null=True)),
                ('totaldiscountprovided', models.FloatField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.invoice')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('percentage', models.FloatField(blank=True, default=0, null=True)),
                ('discoutn_type', models.CharField(blank=True, default='', max_length=164, null=True)),
                ('booking_type', models.CharField(blank=True, default='', max_length=164, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bookingamount',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.discount'),
        ),
        migrations.AddField(
            model_name='bookingamount',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
