# Generated by Django 3.2.5 on 2021-11-22 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0026_forsome_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='forsome',
            name='profile_pic',
            field=models.FileField(default='', max_length=500, null=True, upload_to='user/profile_pic'),
        ),
    ]
