# Generated by Django 3.2.5 on 2021-11-23 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0027_forsome_profile_pic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['updated_at']},
        ),
    ]
