# Generated by Django 4.0.1 on 2022-01-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medias',
            name='media_content',
            field=models.ImageField(blank=True, choices=[(1, 'Image'), (2, 'Video')], default='', null=True, upload_to=''),
        ),
    ]
