# Generated by Django 3.2.5 on 2021-12-06 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211203_1831'),
        ('hospital', '0009_alter_hospitalrooms_department'),
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scheduleDate', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('is_booked', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.labs')),
                ('timeslot', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.timeslot')),
            ],
            options={
                'ordering': ['scheduleDate'],
            },
        ),
    ]
