# Generated by Django 4.0.1 on 2022-01-25 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_hospitaldoctors_admin_hospitaldoctors_admin_and_more'),
        ('lab', '0002_remove_medias_user_medias_lab_medias_pharmacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medias',
            name='lab',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_media', to='accounts.labs'),
        ),
        migrations.AlterField(
            model_name='medias',
            name='pharmacy',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pharma_media', to='accounts.pharmacy'),
        ),
    ]
