# Generated by Django 4.0.1 on 2022-01-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_alter_homevisitcharges_lab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medias',
            name='media_content',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
