# Generated by Django 4.0.1 on 2022-01-20 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_hospitals_specialist'),
        ('radmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitaldisease',
            name='hospital',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hospitaldisease', to='accounts.hospitals'),
        ),
    ]
