# Generated by Django 4.0.1 on 2022-01-22 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_specailist_hover_icon_and_more'),
        ('radmin', '0002_alter_hospitaldisease_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitaldisease',
            name='doctor',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hospitaldoctors_disease', to='accounts.hospitaldoctors'),
        ),
    ]
