# Generated by Django 4.0.1 on 2022-01-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radmin', '0002_donorrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('desc', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('d_icon', models.FileField(default='', max_length=500, null=True, upload_to='')),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
