# Generated by Django 4.0.1 on 2022-01-18 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_patients_added_by_doctor_patients_doctor'),
        ('radmin', '0003_disease'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalDisease',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disease', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='radmin.disease')),
                ('doctor', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.hospitaldoctors')),
                ('hospital', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.hospitals')),
            ],
        ),
    ]
