# Generated by Django 4.0.1 on 2022-01-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radmin', '0003_alter_hospitaldisease_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='d_icon',
            field=models.ImageField(default='', max_length=500, null=True, upload_to=''),
        ),
    ]
