# Generated by Django 4.0 on 2022-01-07 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_hospitaldoctors_is_hospital_added'),
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalstaffdoctors',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospitaldoctor', to='accounts.hospitaldoctors'),
        ),
    ]
