# Generated by Django 3.2.5 on 2021-11-29 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211126_0707'),
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scheduleDate', models.DateField(blank=True, null=True)),
                ('schedule', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('booked', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hospitaldoctors')),
                ('hospital', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.hospitals')),
            ],
        ),
    ]
