# Generated by Django 4.0.1 on 2022-01-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulancedetails',
            name='vehicle_number',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_title',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
