# Generated by Django 4.0.1 on 2022-01-20 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_hospitals_specialist'),
        ('hospital', '0002_alter_hospitalmedias_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalmedias',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitalmedia', to='accounts.hospitals'),
        ),
        migrations.AlterField(
            model_name='hospitalmedias',
            name='media_content',
            field=models.FileField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='hospitalrooms',
            name='hospital',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='hospitalrooms', to='accounts.hospitals'),
        ),
    ]
