# Generated by Django 4.0 on 2022-01-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_alter_hospitalstaffdoctors_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalstaffdoctors',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
    ]
