# Generated by Django 4.0.1 on 2022-01-17 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('hospital', '0002_alter_ambulancedetails_vehicle_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hospitaldoctors'),
        ),
        migrations.AlterField(
            model_name='hospitalstaffdoctors',
            name='doctor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.hospitaldoctors'),
        ),
    ]
