# Generated by Django 3.2.5 on 2021-11-29 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_doctorschedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorschedule',
            old_name='booked',
            new_name='is_booked',
        ),
    ]
