# Generated by Django 4.0.1 on 2022-01-19 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_alter_doctorschedule_doctor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorschedule',
            options={'ordering': ['-scheduleDate']},
        ),
    ]
