# Generated by Django 3.2.5 on 2021-11-29 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_rename_booked_doctorschedule_is_booked'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('schedule', models.TimeField(blank=True, default='', null=True)),
                ('session', models.CharField(blank=True, choices=[(1, '1st'), (2, '2nd'), (3, '3rd')], default='', max_length=200, null=True)),
                ('schedule_type', models.CharField(blank=True, choices=[(15, '15'), (30, '30'), (45, '45'), (60, '60')], default='', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctorschedule',
            name='schedule',
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='timeslot',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.timeslot'),
        ),
    ]
