# Generated by Django 4.0.1 on 2022-01-20 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_hospitals_specialist'),
        ('hospital', '0003_alter_hospitalmedias_hospital_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulancedetails',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitalorder', to='accounts.hospitals'),
        ),
    ]
