# Generated by Django 4.0.1 on 2022-01-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_alter_serviceandcharges_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulancedetails',
            name='profile_pic',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='hospitalspatients',
            name='ID_proof',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
