# Generated by Django 3.2.5 on 2021-11-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_auto_20211129_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='schedule_type',
            field=models.CharField(blank=True, choices=[(15, 15), (30, 30), (45, 45), (60, 60)], default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='session',
            field=models.CharField(blank=True, choices=[(1, 1), (2, 2), (3, 3)], default='', max_length=200, null=True),
        ),
    ]
