# Generated by Django 4.0.1 on 2022-01-20 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_zip_code_hospitaldoctors_pin_code'),
        ('hospital', '0004_alter_ambulancedetails_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulancedetails',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitalambulance', to='accounts.hospitals'),
        ),
    ]
