# Generated by Django 4.0.1 on 2022-01-20 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_alter_ambulancedetails_hospital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitalspatients',
            old_name='zip_Code',
            new_name='pin_code',
        ),
    ]
