# Generated by Django 3.2.5 on 2021-11-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_auto_20211129_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='schedule_type',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='session',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
