# Generated by Django 4.0.1 on 2022-01-21 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_zip_code_patients_pin_code'),
        ('hospital', '0006_rename_zip_code_hospitalspatients_pin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospitaldoctors_blogs', to='accounts.hospitaldoctors'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.hospitals'),
        ),
    ]
