# Generated by Django 3.2.5 on 2021-11-30 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_auto_20211129_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.hospitalstaffdoctors'),
        ),
    ]
