# Generated by Django 4.0.1 on 2022-01-22 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_specailist_hover_icon_and_more'),
        ('hospital', '0007_alter_blog_doctor_alter_blog_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.hospitaldoctors'),
        ),
    ]
