# Generated by Django 3.2.5 on 2021-12-02 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_auto_20211201_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalrooms',
            name='department',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.departments'),
        ),
    ]
