# Generated by Django 4.0.1 on 2022-01-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_alter_doctorschedule_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambulancedetails',
            name='profile_pic.url',
        ),
        migrations.AddField(
            model_name='ambulancedetails',
            name='profile_pic',
            field=models.ImageField(blank=True, default='', null=True, upload_to='hospital/services/images'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='hospital/blog/images'),
        ),
        migrations.AlterField(
            model_name='hospitalmedias',
            name='media_content',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='hospitalspatients',
            name='ID_proof',
            field=models.ImageField(blank=True, default='', null=True, upload_to='patients/profile/images'),
        ),
    ]
