# Generated by Django 3.2.5 on 2021-11-23 05:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0009_hospitalstaffdoctors_is_homevisit_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbulanceDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('drive_name', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('drive_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format +919999999999. Up to 10 digits allowed.', regex='^\\+?1?\\d{9,10}$')], verbose_name='Phone')),
                ('vehicle_type', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('vehicle_number', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('charge', models.FloatField(blank=True, default=0.0, null=True)),
                ('Area', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
