# Generated by Django 3.2.5 on 2021-11-23 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20211123_1042'),
        ('hospital', '0010_ambulancedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulancedetails',
            name='ambulance_with',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ambulancedetails',
            name='occupied',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ambulancedetails',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hospitals'),
        ),
    ]
