# Generated by Django 3.2.5 on 2021-11-23 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0011_auto_20211123_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambulancedetails',
            name='ambulance_with',
        ),
        migrations.AddField(
            model_name='ambulancedetails',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospitalstaffdoctors'),
        ),
    ]
