# Generated by Django 3.2.5 on 2021-11-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_auto_20211123_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulancedetails',
            name='occupied',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='ambulancedetails',
            name='vehicle_number',
            field=models.CharField(blank=True, default='', max_length=500, null=True, unique=True),
        ),
    ]
