# Generated by Django 3.2.5 on 2021-11-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_auto_20211123_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulancedetails',
            name='ID_proof',
            field=models.FileField(blank=True, default='', null=True, upload_to='hospital/services/images'),
        ),
    ]
