# Generated by Django 3.2.5 on 2021-11-23 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20211123_1042'),
        ('hospital', '0015_rename_id_proof_ambulancedetails_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_title', models.CharField(blank=True, default='', max_length=500, null=True, unique=True)),
                ('blog_content', models.TextField(blank=True, default='', max_length=5000, null=True)),
                ('blog_image', models.FileField(blank=True, default='', null=True, upload_to='hospital/blog/images')),
                ('is_active', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospitalstaffdoctors')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hospitals')),
            ],
        ),
    ]
